version: '3'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-meetups}
      WS_DB: ${WS_DB:-meetups_ws}
    ports:
      - "5555:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_volume:
